model = "gpt-5-codex"
tools.web_search = true
model_reasoning_effort = "medium"

[projects."/home/mirza/configs"]
trust_level = "trusted"

[projects."/Users/Y_ALTAY1/Documents/configs"]
trust_level = "trusted"

[projects."/Users/Y_ALTAY1/Documents/comisTestMCP"]
trust_level = "trusted"

[projects."/home/mirza/Documents/Projects/measureApp"]
trust_level = "trusted"

[projects."/Users/Y_ALTAY1/Documents/logitech-sngr-rezai-email"]
trust_level = "trusted"

[projects."/home/mirza/Documents/Projects/purrsuitApp"]
trust_level = "trusted"

[projects."/home/mirza/Documents/Projects/zumrudu-anka"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.supabase]
command = "npx"
args = ["-y", "@supabase/mcp-server-supabase@latest", "--project-ref=kxtmkvxkbmtnaamtlxeu"]
env = { SUPABASE_ACCESS_TOKEN = "" } 
startup_timeout_ms = 20_000 
enabled=false

network_access = true
